language: node_js
node_js:
- node
after_success:
- coveralls < coverage/lcov.info
- npm run-s build
- pwd
- ls
- ls dist
- test $TRAVIS_BRANCH = "main" && cd example && npm install &&
  npm run build && cd ..
deploy:
- provider: pages
  local_dir: example/build
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: main
- provider: npm
  email: devs@ginkgobioworks.com
  api_key: "$NPM_TOKEN"
  on:
    tags: true
    repo: ginkgobioworks/react-json-schema-form-builder
env:
  global:
  - secure: Flqu795ioTwg6u3/v/Gf7quuH/d3OVCLj0IYnr7U9beYWqsILKfe1mh/gQ6yjku5Gx32+sroXdo7t1/qr1ZIdw+eWqDS7DIQtNTlXO5l6U1FpvtvSe7WQdHqalcIPrPYffLhv/w/+qZV1yC6tiZRAbujknn046MVIcWshrz3A4UjRMiViRgxW0GFpG17qv3XbnqYqItfLsF5Uz7ZnJ7NGEeodelHe6G1bkS1ovGsrS2vxCr7DQtzFzRSCSEfHharpqudD8cHjs9E1zEoz5Gvn7AU9hMwckk8TYeqA16eaiBiSs7KzfHZirZDfS9XYmUJO8KcAWOvbajiVCgfjBXK9nVsT+j2kb0uouQtV7+AC42ENTw1Rbrbi5fwhWrSmAOKumXqmBbBdxOOpF1zeSjwVMugOFDCz2LkNCMxSEhkI3cUmYbsxaB+5DAn9AmSCazbIq+0OOo0SDBggUn2mvxfg/XGyiBk/0qj3CAsnCiGpI+NyzGBK+1DaBRahMe58FlBEQlD0/uHD1ABYrzlr2DIhBzPBSz2J4h2VeX7ftuoSyE3Hrcdgm13lKgBdfkcEFTzTSCA3Mfw0ZCPeoIQJSC4u0Q/ipI47DbFXN5/e73hwyLZvVDcCEWYnV++ffV6x6vyTroU3oamSN9G4cddTjhRmTQCI2a4QiXtAKyUFp+nYTk=
  - secure: EKTkEcwhzoA8le0BFFnSzQngZVWvwhN0dM5YZH/Yz/E9D75PoIlelJEL8FTdAAb04+Ux17E0FhMODFX1f6lM2JVmE0WML9M/i9YYvfqF+TtftbW0ZbaTNxOgkBp+NfMYxAxktjo+6EyAP3t5QyD7y/zogNKrMb6aAZYbOR/V0F+F/RFSJHDh/U9wwpOEDs2g6rVTMLDGDY6j3pziQi25kaeYgkAAhczzKDRTPqY1wWe8kQTjpsCIugMLF9Q8JeNSxtgAtH/87Emv00v0FBOED4i/c6jLC4DSbtjtJfrhWbDbxouliInoLSkj1UQVGNj85Yvdmleqk5AHp1gHGvWXmVPQHk4uW++1OPx+pO87chLf+VtFUkxzGXl/SKCpFNwsv5jzHiqa+Jo1md/Yxs0CNCjtI/e1xmzBwQVGPv1+Jl57Y8WzmB0cOqYrLLoEfleLR+u/zELiirPporiEk3oK6v2DiaHWLHoY/ed8ahVbJ0mZyKClKgMG6cTJgtRJeLzRNO7vHolmrddE3bcpa723Qum3XXhdDl+Q/YrXQAxWSj8BDS+LqRuAbwjpnWnZ/Nfuap9DyjSlC5KCnYyb/xQgM2Y+MMT8G3RbxUYL3bB3Upy5HR7deWD8YbH75VyouPZlSpruhn4Qwd5flxgLAfG0svj6GpBZ8J0lQ7zXYLTv+NU=
